### ISSUE TITLE
ImportError: cannot import name 'Gaussian' from 'internal.utils.gaussian_utils'

### ISSUE THREAD

**Issue by Verius50** [Linketic/CityGaussian#126]
I must have found a bug:
internal.utils.gaussian_utils.py 
has `class GaussianPlyUtils:`
and if I replace `Gaussian` in ply2ckpt.py on `GaussianPlyUtils`
I get this error:
```
(gspl) C:\CityGaussian>python utils\ply2ckpt.py "E:\AFS\Data\Rudnevo_20250207_ADS_Mavic\POSTSHOT_testing\Block4(156)\MCMC_3m.ply" --reference "E:\AFS\Data\Rudnevo_20250207_ADS_Mavic\blocks\block_4\checkpoints\epoch=127-step=19999.ckpt"
Searching checkpoint file...
Loading checkpoint 'E:\AFS\Data\Rudnevo_20250207_ADS_Mavic\blocks\block_4\checkpoints\epoch=127-step=19999.ckpt'...
Converting...
Traceback (most recent call last):
  File "C:\CityGaussian\utils\ply2ckpt.py", line 51, in <module>
    checkpoint["state_dict"]["gaussian_model._features_extra"] = model.real_features_extra
AttributeError: 'GaussianPlyUtils' object has no attribute 'real_features_extra'
```
And GaussianPlyUtils really has no attribute 'real_features_extra'

What should i do?
help me please, z want to convert .ply file to checkpoint format

@DekuLiuTesla

**Comment by DekuLiuTesla** [comment]
@Verius50 Thanks for your feedback! The ply2ckpt.py is mainly used in the old version of Gaussian Lightning, and it has been deleted in its v0.10.1. This tool is used in our experiments but accidentally ignored when rebasing to the latest version of Gaussian Lightning. If you do need this function, you can try:
```python
import add_pypath
import os
import argparse
import lightning
import torch
from internal.utils.gaussian_utils import GaussianPlyUtils
from internal.utils.gaussian_model_loader import GaussianModelLoader
from internal.utils.vq_utils import read_ply_data, write_ply_data, load_vqgaussian

parser = argparse.ArgumentParser()
parser.add_argument("input")
parser.add_argument("--reference", "-r", required=True, default=None)
parser.add_argument("--output", "-o", required=False, default=None)
parser.add_argument("--sh_degree", "-s", required=False, default=3, type=int)
args = parser.parse_args()

# search input file
print("Searching checkpoint file...")
load_file = GaussianModelLoader.search_load_file(args.reference)
assert load_file.endswith(".ckpt"), f"Not a valid reference ckpt file can be found in '{args.reference}'"

if args.sh_degree == 3:
    sh_dim = 3+45
elif args.sh_degree == 2:
    sh_dim = 3+24

print(f"Loading checkpoint '{load_file}'...")
checkpoint = torch.load(load_file)
print("Converting...")
if os.path.exists(os.path.join(args.input, 'extreme_saving')):
    dequantized_feats = load_vqgaussian(os.path.join(args.input,'extreme_saving'), device='cuda')
    checkpoint["state_dict"]["gaussian_model._xyz"] = dequantized_feats[:, :3]
    checkpoint["state_dict"]["gaussian_model._features_dc"] = dequantized_feats[:, 6:9].reshape(dequantized_feats.shape[0], 1, 3)
    checkpoint["state_dict"]["gaussian_model._features_rest"] = dequantized_feats[:, 9:6+sh_dim].reshape(dequantized_feats.shape[0], -1, 3)
    checkpoint["state_dict"]["gaussian_model._opacity"] = dequantized_feats[:, -8:-7]
    checkpoint["state_dict"]["gaussian_model._scaling"] = dequantized_feats[:, -7:-4]
    checkpoint["state_dict"]["gaussian_model._rotation"] = dequantized_feats[:, -4:]
    checkpoint["state_dict"]["gaussian_model._features_extra"] = torch.empty(dequantized_feats.shape[0], 0).to('cuda')
    checkpoint['hyper_parameters']['gaussian'].sh_degree = args.sh_degree
    if args.output is None:
        args.output = os.path.join(args.input, 'checkpoints', args.reference.split("/")[-1])
    
elif args.input.endswith(".ply"):
    model = GaussianPlyUtils.load_from_ply(args.input, sh_degrees=args.sh_degree).to_parameter_structure()
    checkpoint["state_dict"]["gaussian_model._xyz"] = model.xyz
    checkpoint["state_dict"]["gaussian_model._opacity"] = model.opacities
    checkpoint["state_dict"]["gaussian_model._features_dc"] = model.features_dc
    checkpoint["state_dict"]["gaussian_model._features_rest"] = model.features_rest
    checkpoint["state_dict"]["gaussian_model._scaling"] = model.scales
    checkpoint["state_dict"]["gaussian_model._rotation"] = model.rotations
    checkpoint["state_dict"]["gaussian_model._features_extra"] = torch.empty(model.xyz.shape[0], 0).to('cuda')
    checkpoint['hyper_parameters']['gaussian'].sh_degree = args.sh_degree
    if args.output is None:
        os.makedirs(os.path.join(args.input[:args.input.rfind("/")], 'checkpoints'), exist_ok=True)
        args.output = os.path.join(args.input[:args.input.rfind("/")], 'checkpoints', args.reference.split("/")[-1])
torch.save(checkpoint, args.output)

print(f"Saved to '{args.output}'")

```
But to get rendering result, a config file is further required.

**Comment by Zogne** [comment]
Hey, @DekuLiuTesla (@Verius50 is my friend, we're working together)
Thanks! It works nice.
But here's the problem:
When I convert .ply file generated by foreign application (e.g. Jawset Postshot) into .ckpt, and then back into .ply it worsens the original quality for some reason.
It doesn't seem to be something related to block trimming.
I'm really excited of CityGaussian feature to merge blocks.
Any ideas?
Thanks!

![Image](https://github.com/user-attachments/assets/dab12ea7-c55b-42da-ae18-f59e3046a2de)

Here's YAML config file of `.ckpt` file that was used as `--reference` for running **ply2ckpt.py**
```yaml
model:
  overwrite_config: False
  # initialize_from: C:\CityGaussian\outputs\Rudnevo_RCM1_5x5_Block#4\blocks\block_4\checkpoints\epoch=63-step=9999.ckpt
  gaussian:
    class_path: internal.models.gaussian_2d.Gaussian2D
    init_args:
      sh_degree: 2
      optimization:
        means_lr_init: 1.6e-5
        means_lr_scheduler:
          lr_final: 1.6e-6
          max_steps: 30_000
        scales_lr: 0.001
  metric:
    class_path: internal.metrics.citygsv2_metrics.CityGSV2Metrics
    init_args:
      lambda_normal: 0.0125
      normal_regularization_from_iter: 0
      depth_normalized: true
      depth_loss_type: l1+ssim
      depth_loss_ssim_weight: 1.0
      depth_loss_weight:
        init: 1.0
        final_factor: 0.1
        max_steps: 60_000
  renderer: 
    class_path: internal.renderers.sep_depth_trim_2dgs_renderer.SepDepthTrim2DGSRenderer
    init_args:
      depth_ratio: 1.0
      diable_trimming: true
  density: 
    class_path: internal.density_controllers.citygsv2_density_controller.CityGSV2DensityController
    init_args:
      densification_interval: 1000
      opacity_reset_interval: 20_000
      densify_from_iter: 4000
      densify_until_iter: 30_000
      densify_grad_threshold: 0.00005
trainer:
  check_val_every_n_epoch: 20
  max_steps: 30000
data:
  path: E:\AFS\Data\Rudnevo_20250207_ADS_Mavic
  parser:
    class_path: EstimatedDepthBlockColmap
    init_args:
      down_sample_factor: 1
      depth_scale_lower_bound: 0.01
      depth_scale_upper_bound: 50.0
      content_threshold: 0.01
      block_dim:
      - 5
      - 5
save_iterations:
- 10000
- 20000
- 30000
```
