### ISSUE TITLE
Slow training after almost reaching GPU memory limit

### ISSUE THREAD

**Issue by Zogne** [Linketic/CityGaussian#131]
I have limited memory on my PCs (24GB and 16GB), which is far from 40GB, that I've heard you guys using.
The thing is, when I train blocks for too long, GPU memory usage increases.
And when it almost reaches GPU max memory limit: 
![Image](https://github.com/user-attachments/assets/244bdde4-a8fb-48ff-9d71-78417798c474)
It doesn't crash, which is nice though, but instead, it **slows down drastically**:
![Image](https://github.com/user-attachments/assets/06b2ce38-2e31-4409-8916-2c86ba5d68f8)

I scratched my head for a while, decided to save .ckpt and the exact moment it starts lagging out, and then loaded it via "initialize_from" (it's hacky, ikr) to keep on training. It helped for 10k iterations ahead, but then, even with "initialize_from" trick, I got around 0.02it/s instead of normal 2.00it/s

I'm using 2600x1949 photos, that is downsampled by 2. Original dimensions are 5200x3898. Average photo count: 1200 (per single partition). There's no way I'm downsampling further, cuz I need that quality so bad.

I tried prune_ratio of 0.75, it helped a little bit (should I try increasing it even more?)

I think I need some way to limit splat count, or something like that.
Cuz **.ckpt file size keeps growing and so does the GPU memory usage**

I'm using Windows 10, RTX 3090, RTX 4080, RTX 4090

BTW, does CityGaussianV2 trim sparse data to work with specific partition only that I'm training? Cuz our sparse data covers pretty large area (283 MB)

That's my config file for training:
```yaml
model:
  overwrite_config: False
  gaussian:
    class_path: internal.models.gaussian_2d.Gaussian2D
    init_args:
      sh_degree: 2
      optimization:
        means_lr_init: 1.6e-5
        means_lr_scheduler:
          lr_final: 1.6e-6
          max_steps: 30_000
        scales_lr: 0.001
  metric:
    class_path: internal.metrics.citygsv2_metrics.CityGSV2Metrics
    init_args:
      lambda_normal: 0.0125
      normal_regularization_from_iter: 0
      depth_normalized: true
      depth_loss_type: l1+ssim
      depth_loss_ssim_weight: 1.0
      depth_loss_weight:
        init: 1.0
        final_factor: 0.1
        max_steps: 60_000
  # metric: internal.metrics.mcmc_metrics.MCMCMetrics
  renderer: 
    class_path: internal.renderers.sep_depth_trim_2dgs_renderer.SepDepthTrim2DGSRenderer
    init_args:
      depth_ratio: 1.0
      start_prune_ratio: 0.75
      prune_ratio: 0.75
      diable_trimming: true
  density: 
    class_path: internal.density_controllers.citygsv2_density_controller.CityGSV2DensityController
    init_args:
      densification_interval: 1000
      opacity_reset_interval: 20_000
      densify_from_iter: 4000
      densify_until_iter: 30_000
      densify_grad_threshold: 0.00005
  # density: internal.density_controllers.mcmc_density_controller.MCMCDensityController
trainer:
  check_val_every_n_epoch: 20
  max_steps: 30000
data:
  val_max_num_images_to_cache: 256
  test_max_num_images_to_cache: 256
  train_max_num_images_to_cache: 256
  path: \\192.168.11.88\MSP_Data_WS3D\AFS\Rudnevo_20250207_ADS_Mavic_d2
  parser:
    class_path: EstimatedDepthBlockColmap
    init_args:
      down_sample_factor: 2
      depth_scale_lower_bound: 0.01
      depth_scale_upper_bound: 50.0
      content_threshold: 0.01
      block_dim:
      - 4
      - 4
cache_all_images: false
save_iterations:
- 1000
- 5000
- 10000
- 20000
- 30000
```

Help me please 😣😣😣 @DekuLiuTesla
